### ISSUE TITLE
[PE-D] Misleading documentation in `get` command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-3/tp#163]
The UG mentioned that when names are entered in the `get` command is similar to the `filter` command which is case insensitive.

![Screenshot 2021-10-29 at 4.39.12 PM.png](https://raw.githubusercontent.com/Javiier-pzk/ped/main/files/61c25db7-1806-4ade-8161-7057c9a2f3bc.png)

But finding trying to get a name is in fact case sensitive

![Screenshot 2021-10-29 at 4.42.48 PM.png](https://raw.githubusercontent.com/Javiier-pzk/ped/main/files/3317cbe3-b583-4496-9431-d1c4c3e2839a.png)

Perhaps the UG could specifically mention that names are case insensitive or it the team could implement a case insensitive name search

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Javiier-pzk/ped#2

**Comment by Amadeus-Winarto** [comment]
Resolved in #213
