### ISSUE TITLE
[PE-D] [T15-3] Hard to use feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-3/tp#168]
![image.png](https://raw.githubusercontent.com/YaleChen299/ped/main/files/1c4872b9-3e26-4dd9-ba9f-a5bc5a786acf.png)

Results provided is in a small screen and can be organised in a better way.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: YaleChen299/ped#3

**Comment by jianoway** [comment]
> Should add comment stating that the output will be in default order.

**Comment by Amadeus-Winarto** [comment]
Resolved
