### ISSUE TITLE
[PE-D]  Error message for participation command inconsistent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-3/tp#169]
When entering a very large value for participation command, the error message says it is the invalid format, when it should say that the value of participation points is not correct.

![image.png](https://raw.githubusercontent.com/wowsiddanth/ped/main/files/be5b58c3-3991-4123-9f64-f59bb8a2f28e.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: wowsiddanth/ped#10

**Comment by jianoway** [comment]
Duplicate issue raised by #186
