### ISSUE TITLE
[PE-D] Total grade incorrect after adding a grade

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-3/tp#171]
Steps to reproduce:
* add n/Daby e/hi@u.nus.edu te/@hi p/99999999
* grade 1 as/RA1 g/100
* view 1
* click view test score

Expected:
total score to be NA or 100

Actual:
total score: 96

![image.png](https://raw.githubusercontent.com/sherrpass/ped/main/files/a78041af-b787-4f63-b280-bc30d863bf1c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: sherrpass/ped#4

**Comment by cheweejia** [comment]
#167 #166

**Comment by cheweejia** [comment]
#166
