### ISSUE TITLE
[PE-D] Cannot add tags with more than one word

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-3/tp#175]
It is reasonable to want to add tags with multiple words, for example `good friend`.

![image.png](https://raw.githubusercontent.com/wowsiddanth/ped/main/files/a7e039df-adfe-4f8f-a77d-b1c6339557ab.png)

![image.png](https://raw.githubusercontent.com/wowsiddanth/ped/main/files/cdbffdae-45c2-45d5-904e-de79e54a4a18.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: wowsiddanth/ped#12

**Comment by cheweejia** [comment]
Allow tags with more than one word (either that or we specify the restriction and keep it to a single word, open to discussion)
