### ISSUE TITLE
[PE-D] Inconsistent error message for grade command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-3/tp#180]
The error message says that number can be used, whilst the user guide says only integers can be used.

![image.png](https://raw.githubusercontent.com/wowsiddanth/ped/main/files/6427050e-af3b-4637-96ef-9f4e2edb4b69.png)

![image.png](https://raw.githubusercontent.com/wowsiddanth/ped/main/files/10e8d28a-1573-4c3a-a416-cedc92ec437b.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: wowsiddanth/ped#13

**Comment by cheweejia** [comment]
Update error message in Grade
