### ISSUE TITLE
[PE-D] External changes on the data file are not recorded in the commit history

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-3/tp#191]
Currently, the product allows advanced users to make changes directly to the json data file. However, when these changes are made and the product is launched, the update to the data is not stored as a commit. As a result, this leads to some unforeseen side effects when changing commit version, such as doing an `undo` and then a `redo` would simply erase the changes to the json file.

Expected:
Changing the json file externally should be saved as a commit.

Actual:
The change is not recorded as a commit. Moving back and forth from the commit or reverting to the same commit version will revert external changes made.

**Steps to reproduce bug**:
1. Use the `history` command to check current commit version.
2. Open up the json file, and edit one of the values there. (E.g. Change the name from "Alex" to "Zero").<br>
![Screenshot 2021-10-29 at 7.09.50 PM.png](https://raw.githubusercontent.com/szelongq/ped/main/files/803d4f9e-1f7f-407f-ad12-dd7b5c2a6f4b.png)

3. Launch the jar file.
4. Use the `history` command to check current commit version again. Note that it is still the same, but the change in json file has been applied. (E.g. Name is "Zero" instead of "Alex")

![Screenshot 2021-10-29 at 7.11.13 PM.png](https://raw.githubusercontent.com/szelongq/ped/main/files/fe2a48d8-7a0a-4c4f-8373-cbadc9c4512c.png)

5. Undo
6. Redo. Now the change in json file has been reverted. (E.g. Name is "Alex" again)

![Screenshot 2021-10-29 at 7.07.32 PM.png](https://raw.githubusercontent.com/szelongq/ped/main/files/04e2d3e5-5fc3-42ff-bf7d-6c20ea6264c1.png)
![Screenshot 2021-10-29 at 7.08.03 PM.png](https://raw.githubusercontent.com/szelongq/ped/main/files/b5e1246f-48ff-442f-9550-e08f812bf734.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: szelongq/ped#7

**Comment by Amadeus-Winarto** [comment]
Internal version control is not intended to keep track of changes made outside of the application. While this can be a possible, useful feature to add-on in the future, it doesn't seem to be very critical to solve it now
